name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: jvm
            os: ubuntu
          - target: js
            os: ubuntu
          - target: wasmJs
            os: ubuntu
          - target: wasmWasi
            os: ubuntu
          - target: linuxX64
            os: ubuntu
          - target: macosArm64
            os: macos
          - target: mingwX64
            os: windows
          - target: iosSimulatorArm64
            os: macos
          - target: tvosSimulatorArm64
            os: macos
          - target: watchosSimulatorArm64
            os: macos
    runs-on: "${{ matrix.os }}-latest"
    name: "test (${{ matrix.target }})"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-java@v4"
        with:
          distribution: "temurin"
          java-version: 21
      - run: "./gradlew core:${{ matrix.target }}Test"
